version: '3.0'
networks:
  docker-network:
    driver: bridge
services:
  alijomehri-php-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "docker-alijomehri-php-web"
    working_dir: "/var/www/html"
    volumes:
      - "../src:/var/www/html"
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9900:9000"
    networks:
      - docker-network
  alijomehri-web:
    image: nginx:stable-alpine
    container_name: "docker-alijomehri-web"
    restart: unless-stopped
    working_dir: "/var/www/html"
    ports:
      - "9085:80"
    volumes:
      - "../src:/var/www/html"
      - "./nginx/web/logs:/var/log/nginx"
      - "./nginx/web/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - alijomehri-php-web
      - alijomehri-mysql
      - alijomehri-rabbitmq
    links:
      - alijomehri-mysql
      - alijomehri-rabbitmq
    networks:
      - docker-network
  alijomehri-mysql:
    image: mysql:8.0.25
    container_name: "docker-alijomehri-mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    volumes:
      - "./~mysql/dbdata:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "lkjasd$%;lk987FdwL9(k"
      SERVICE_TAGS: dev
      SERVICE_NAME: alijomehri-mysql
    networks:
      - docker-network
  alijomehri-rabbitmq:
    container_name: "alijomehri-rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=asdlkjasd435897%K
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - docker-network